# Test
language: node_js
node_js:
  - "7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
jobs:
  include:
    -stage: testClient
     script: npm run testClient
    -stage: testServer
     script: npm run testServer
branches:
  only:
    - master
    - userSearch
