version: "3"
services:
  web:
    image: techmexdev/codeup:latest
    command: "npm run production"
    ports:
      - "3034:3034"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: "mongo"
    ports:
     - "27017:27017"
